### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by stevespringett** [DependencyTrack/gh-upload-sbom#5]
There have been a few PRs lately and we need to release v1.1.0 as a result.

Not sure how to release new actions. There doesn't appear to be a release script or action in the repo to do so.

**Comment by k3rnelpan1c-dev** [comment]
I can answer this one. For GitHub JavaScript Actions you can simply create a GitHub release, and that will publish the release to the GitHub Actions Marketplace. This works since the `action.yaml` points at the `index.js` and that will get executed by the runner environment (as you currently set it in node12).

As Node12 is on the decline and `node16` is available I would recommend bumping that in the `action.yaml` too (just my 2 cents)

---

### Unrelated, yet here as additional context if this where a TypeScript Action:

If this where a TypeScript action you would have to "compile" it down to JS again and check in the resulting "compiled" files that then get referred to by the `action.yaml` and executed by the Action environment again.

**Comment by donaldedwin** [comment]
> I can answer this one. For GitHub JavaScript Actions you can simply create a GitHub release, and that will publish the release to the GitHub Actions Marketplace. This works since the `action.yaml` points at the `index.js` and that will get executed by the runner environment (as you currently set it in node12).
> 
> As Node12 is on the decline and `node16` is available I would recommend bumping that in the `action.yaml` too (just my 2 cents)
> 
> ### Unrelated, yet here as additional context if this where a TypeScript Action:
> If this where a TypeScript action you would have to "compile" it down to JS again and check in the resulting "compiled" files that then get referred to by the `action.yaml` and executed by the Action environment again.

Definitely, Its already caught on. Action is practically useless at the moment, GitHub deprecated Node12 already so yup :( And there hasn't been much movement on this repo in 6 months

**Comment by colorfulape** [comment]
I highly recommend tagging a commit and then using this tag for a GitHub release.

**Comment by nscuro** [comment]
Released v2.0.0 / v2 which bumps the NodeJS version to 16.
